

---- INSTRUMENTS inserts
INSERT INTO instrument_inv (INSTRUMENT_ID, CREATED_BY, CREATED_ON, INSTRUMENT_NAME) VALUES (1001, 'sachin', sysdate, 'Instrument-1');
INSERT INTO instrument_inv (INSTRUMENT_ID, CREATED_BY, CREATED_ON, INSTRUMENT_NAME) VALUES (1002, 'sachin', sysdate, 'Instrument-2');
INSERT INTO instrument_inv (INSTRUMENT_ID, CREATED_BY, CREATED_ON, INSTRUMENT_NAME) VALUES (1003, 'sachin', sysdate, 'Instrument-3');

---- inserts ORDER_BOOK_INV
INSERT INTO ORDER_BOOK_INV (ORDER_BOOK_ID, CREATED_BY, CREATED_ON, ORDER_BOOK_NAME, INSTRUMENT_ID, ORDER_BOOK_STATUS) 
VALUES (1001, 'sachin', sysdate, 'Book-1', 1001, 'OPEN');
INSERT INTO ORDER_BOOK_INV (ORDER_BOOK_ID, CREATED_BY, CREATED_ON, ORDER_BOOK_NAME, INSTRUMENT_ID, ORDER_BOOK_STATUS) 
VALUES (1002, 'sachin', sysdate, 'Book-2', 1002, 'OPEN');


---- inserts ORDERS_INV
INSERT INTO ORDERS_INV (ORDER_ID, CREATED_BY, CREATED_ON, ORDER_NAME, ORDER_QUANTITY, ORDER_PRICE, INSTRUMENT_ID,  ORDER_TYPE,ORDER_BOOK_ID) 
VALUES (1001, 'sachin', sysdate, 'Order-1', 200, 200, 1001, 'MARKET_ORDER',1001);
INSERT INTO ORDERS_INV (ORDER_ID, CREATED_BY, CREATED_ON, ORDER_NAME, ORDER_QUANTITY, ORDER_PRICE, INSTRUMENT_ID,  ORDER_TYPE) 
VALUES (1002, 'sachin', sysdate, 'Order-2', 3, 505, 1001, 'MARKET_ORDER');

---- execution inserts 
INSERT INTO EXECUTION(EXECUTION_ID, CREATED_BY, EXECUTION_NAME, PRICE,order_book_id,qty) VALUES (1001, 'sachin', 'Execution-1', 50,1001,50);
INSERT INTO EXECUTION(EXECUTION_ID, CREATED_BY, EXECUTION_NAME, PRICE,order_book_id,qty) VALUES (1002, 'sachin', 'Execution-2', 502,1002,200);




